# Generated by Django 4.1 on 2022-08-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVT_N1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='fechaDeNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
